# default:
#   before_script:
#     - echo "install"
#     - pwd
#     - whoami

stages:
  - lint
  - deploy


lint:
    stage: lint
    script:
        - echo "lint"
        - phplint php/*.php

deploy:
    stage: deploy
    script:
        - sudo rm -rf /opt/lampp/htdocs/engima
        - cd /opt/lampp/htdocs
        - sudo git clone git@gitlab.informatika.org:if3110-2019-02-k02-12/engima.git